connections:
  - conn_id: postgres_conn
    conn_type: postgres
    host: localhost
    schema:
    login: postgres
    password: postgres
    port: 5432
    extra:
  - conn_id: postgres_conn_pagila
    conn_type: postgres
    host: localhost
    schema: pagila
    login: postgres
    password: postgres
    port: 5432
    extra:
  - conn_id: snowflake_conn
    conn_type: snowflake
    host: https://gp21411.us-east-1.snowflakecomputing.com
    port: 443
    login: $SNOWFLAKE_ACCOUNT_NAME
    password: $SNOWFLAKE_PASSWORD
    schema: ASTROFLOW_CI
    extra:
      account: "gp21411"
      region: "us-east-1"
      role: "PROVIDERSUSER"
      warehouse: ROBOTS
      database: SANDBOX
  - conn_id: snowflake_conn_1
    conn_type: snowflake
    host: https://gp21411.us-east-1.snowflakecomputing.com
    port: 443
    login: $SNOWFLAKE_ACCOUNT_NAME
    password: $SNOWFLAKE_PASSWORD
    extra:
      account: "gp21411"
      region: "us-east-1"
      role: "AIRFLOW_TEST_USER"
      warehouse: ROBOTS
  - conn_id: bigquery
    conn_type: bigquery
    description: null
    extra:
      project: "astronomer-dag-authoring"
    host: null
    login: null
    password: null
    port: null
    schema: null
  - conn_id: sqlite_conn
    conn_type: sqlite
    host: /tmp/sqlite.db
    schema:
    login:
    password:
  - conn_id: gcp_conn
    conn_type: google_cloud_platform
    description: null
    extra: null
  - conn_id: aws_conn
    conn_type: aws
    description: null
    extra: null
  - conn_id: gcp_conn_project
    conn_type: google_cloud_platform
    description: null
    extra:
      project: "astronomer-dag-authoring"
      project_id: "astronomer-dag-authoring"
  - conn_id: sftp_conn
    conn_type: sftp
    host: $SFTP_HOSTNAME
    login: $SFTP_USERNAME
    password: $SFTP_PASSWORD
    port: 2222
