---
ci:
  skip:
    - mypy  # requires additional dependencies in ci
    - identity  # output is too verbose for ci; pre-commit.ci truncates almost all output after that
default_stages: [commit, push]
default_language_version:
  # force all unspecified python hooks to run python3
  python: python3
minimum_pre_commit_version: "1.20.0"
repos:
  - repo: meta
    hooks:
      - id: identity
      - id: check-hooks-apply

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: pretty-format-json
        args: ['--autofix']
      - id: name-tests-test
        args: ['--pytest-test-first']
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: rst-backticks
      - id: python-no-log-warn
      - id: python-check-mock-methods

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.4.2
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
      - id: forbid-tabs
        exclude: ^mk/|^docs/Makefile|^Makefile$
      - id: remove-tabs
        exclude: ^mk/|^docs/Makefile|^Makefile$

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        # Exclude auto-generated example files from being changed
        args: ["--config", "pyproject.toml"]

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.13.0
    hooks:
      - id: blacken-docs
        alias: black
        additional_dependencies: [black>=22.10.0]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.257'
    hooks:
      - id: ruff
        args:
        - --config=./ruff.toml

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        name: Run codespell to check for common misspellings in files
        language: python
        types: [text]
        exclude: ^mk/.*\.mk$|^tests/modified_constraint_file.txt$
  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: 'v1.1.1'
      hooks:
      - id: mypy
        name: mypy-uto
        additional_dependencies: [ types-PyYAML, types-requests, types-attrs, attrs ]
        files: "^src/"
        args: ['--follow-imports=normal']

  -   repo: https://github.com/asottile/pyupgrade
      rev: v3.3.1
      hooks:
      -   id: pyupgrade
          args: [--py37-plus]
