---
contact_links:
  - name: Ask a question or get support (Forum)
    url: https://github.com/astronomer/apache-airflow-provider-transfers
    about: Ask a question or request support for using this package
